### ISSUE TITLE
Two "Create new note" one after another in sequence

### ISSUE THREAD

**Issue by mircofranzago** [dperrymorrow/example-backbone-app#5]
From the main page:
1) click on "Create new note"
2) insert data in the form
3) click on "Save"
4) click again on "Create new note"
5) insert data in the form
6) if you click on "Save", something bad happen, it does not work.
This is a screenshot of the error message from the console:
<img width="782" alt="screen shot 2016-05-20 at 18 41 46" src="https://cloud.githubusercontent.com/assets/820293/15435077/98bc9e28-1eba-11e6-9783-146c0a53a29a.png">

**Comment by dperrymorrow** [comment]
Thanks for noticing that, it was because i had been assigning an id in my models and I needed to let local storage do that. 

the `javascript collection.add(this.model)` was being rejected because of duplicate id, and then since it was not in the local storage collection, when i called `save` on the model. It attempted to save via normal http methods, and with no url present, it failed.
